import { useState } from "react";
import { motion } from "framer-motion";
import { ArrowLeft, ChevronDown, Search } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { Input } from "@/components/ui/input";

const faqs = [
  { q: "What is TradeWay?", a: "TradeWay is an AI-powered forex trading platform that automatically trades on your behalf using advanced algorithms. You add capital, and our AI engine handles trade execution across 50+ currency pairs." },
  { q: "What is the minimum capital required?", a: "The minimum capital to start trading is ₹50,000 (approximately $500 USD). This ensures the AI has enough margin to execute profitable trades safely." },
  { q: "How do I add capital?", a: "Go to the Wallet section, enter the amount, choose Bank Transfer, and complete the payment. Share the UTR number and payment screenshot. Capital reflects within 24 hours after verification." },
  { q: "How are profits calculated?", a: "Profits are generated by our AI trading engine and settled daily at 12:00 AM. A 20% platform fee is deducted from gross profits. Net profits are credited to your account automatically." },
  { q: "How do I withdraw my profits?", a: "You can withdraw profits anytime from the Wallet section. Add your bank account first, then submit a withdrawal request. Withdrawals are processed within 24-48 hours to your registered bank account." },
  { q: "What is the referral program?", a: "You earn a percentage of the capital added by users you refer. Step A (Direct): 1%, Step B (Second level): 0.50%, Step C (Third level): 0.25%. Earnings are credited daily at settlement." },
  { q: "Is my money safe?", a: "Your capital is managed with institutional-grade risk management. All data is encrypted end-to-end and we follow strict security protocols." },
  { q: "What documents are needed for KYC?", a: "We only require your Aadhaar card — front and back images. KYC verification is completed within 24 hours." },
  { q: "How does the AI trade?", a: "Our AI engine analyzes market conditions 24/7 using machine learning models. It identifies high-probability setups across 50+ forex pairs and executes trades with strict risk management." },
  { q: "Can I lose my capital?", a: "While forex trading carries inherent risk, our AI uses strict stop-loss mechanisms and position sizing to protect your capital. Historical drawdowns have been minimal." },
];

export default function FAQPage() {
  const navigate = useNavigate();
  const [openIndex, setOpenIndex] = useState<number | null>(null);
  const [search, setSearch] = useState("");

  const filtered = faqs.filter(f => f.q.toLowerCase().includes(search.toLowerCase()) || f.a.toLowerCase().includes(search.toLowerCase()));

  return (
    <div className="min-h-screen bg-background pb-10">
      <div className="px-5 pt-6 pb-4 flex items-center gap-3">
        <button onClick={() => navigate("/help-center")} className="w-10 h-10 rounded-2xl panel-muted flex items-center justify-center">
          <ArrowLeft className="w-4 h-4" />
        </button>
        <div>
          <p className="text-[10px] uppercase tracking-[0.22em] text-primary font-semibold">Help center</p>
          <h1 className="text-xl font-display font-extrabold">FAQs</h1>
        </div>
      </div>

      <div className="px-5 mb-4">
        <div className="relative">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
          <Input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search questions..." className="h-11 rounded-2xl border border-border/60 bg-secondary/30 pl-10 text-sm" />
        </div>
      </div>

      <div className="px-5 space-y-2">
        {filtered.map((faq, i) => (
          <motion.div key={i} initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: i * 0.03 }} className="panel rounded-[1.4rem] overflow-hidden">
            <button onClick={() => setOpenIndex(openIndex === i ? null : i)} className="w-full flex items-center justify-between px-4 py-3.5 text-left">
              <p className="text-sm font-semibold pr-3">{faq.q}</p>
              <ChevronDown className={`w-4 h-4 text-muted-foreground shrink-0 transition-transform ${openIndex === i ? "rotate-180" : ""}`} />
            </button>
            {openIndex === i && (
              <div className="px-4 pb-4">
                <p className="text-xs text-muted-foreground leading-relaxed">{faq.a}</p>
              </div>
            )}
          </motion.div>
        ))}
        {filtered.length === 0 && (
          <p className="text-center text-sm text-muted-foreground py-10">No questions found</p>
        )}
      </div>
    </div>
  );
}
