// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eoofuhmdqziwchcpcyzj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVvb2Z1aG1kcXppd2NoY3BjeXpqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU3NjE4NTUsImV4cCI6MjA5MTMzNzg1NX0.sRQxEgMQzg8Q-LAHlRTifIk4iQG3vFZqNpzp2zTUcrI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});